# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("DriverAnalyzer")
        MainWindow.resize(1280, 800)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QLayout.SetMinimumSize)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.thread1_bn = QPushButton(self.centralwidget)
        self.thread1_bn.setObjectName("thread1_bn")
        self.horizontalLayout_2.addWidget(self.thread1_bn)
        self.thread2_bn = QPushButton(self.centralwidget)
        self.thread2_bn.setObjectName("thread2_bn")
        self.horizontalLayout_2.addWidget(self.thread2_bn)
        self.thread3_bn = QPushButton(self.centralwidget)
        self.thread3_bn.setObjectName("thread3_bn")
        self.horizontalLayout_2.addWidget(self.thread3_bn)
        self.thread4_bn = QPushButton(self.centralwidget)
        self.thread4_bn.setObjectName("thread4_bn")
        self.horizontalLayout_2.addWidget(self.thread4_bn)
        self.thread5_bn = QPushButton(self.centralwidget)
        self.thread5_bn.setObjectName("thread5_bn")
        self.horizontalLayout_2.addWidget(self.thread5_bn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line = QFrame(self.centralwidget)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.banner = QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.banner.setFont(font)
        self.banner.setTextFormat(QtCore.Qt.RichText)
        self.banner.setAlignment(QtCore.Qt.AlignCenter)
        self.banner.setWordWrap(True)
        self.banner.setIndent(10)
        self.banner.setObjectName("banner")
        self.verticalLayout_4.addWidget(self.banner)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.play_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_bn.sizePolicy().hasHeightForWidth())
        self.play_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.play_bn.setFont(font)
        self.play_bn.setObjectName("play_bn")
        self.verticalLayout.addWidget(self.play_bn)

        self.pause_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_bn.sizePolicy().hasHeightForWidth())
        self.pause_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pause_bn.setFont(font)
        self.pause_bn.setObjectName("pause_bn")
        self.verticalLayout.addWidget(self.pause_bn)

        self.record_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_bn.sizePolicy().hasHeightForWidth())
        self.record_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.record_bn.setFont(font)
        self.record_bn.setObjectName("record_bn")
        self.verticalLayout.addWidget(self.record_bn)
        self.empty_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empty_bn.sizePolicy().hasHeightForWidth())
        self.empty_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.empty_bn.setFont(font)
        self.empty_bn.setObjectName("empty_bn")
        self.verticalLayout.addWidget(self.empty_bn)
        self.setting_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_bn.sizePolicy().hasHeightForWidth())
        self.setting_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.setting_bn.setFont(font)
        self.setting_bn.setObjectName("setting_bn")
        self.verticalLayout.addWidget(self.setting_bn)
        self.exit_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_bn.sizePolicy().hasHeightForWidth())
        self.exit_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.exit_bn.setFont(font)
        self.exit_bn.setObjectName("exit_bn")
        self.verticalLayout.addWidget(self.exit_bn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.main_video_layout = QVBoxLayout()
        self.main_video_layout.setObjectName("main_video_layout")
        self.horizontalLayout_5.addLayout(self.main_video_layout)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.model1_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model1_bn.sizePolicy().hasHeightForWidth())
        self.model1_bn.setSizePolicy(sizePolicy)
        self.model1_bn.setText("")
        self.model1_bn.setObjectName("model1_bn")
        self.verticalLayout_2.addWidget(self.model1_bn)
        self.model2_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model2_bn.sizePolicy().hasHeightForWidth())
        self.model2_bn.setSizePolicy(sizePolicy)
        self.model2_bn.setText("")
        self.model2_bn.setObjectName("model2_bn")
        self.verticalLayout_2.addWidget(self.model2_bn)
        self.model3_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model3_bn.sizePolicy().hasHeightForWidth())
        self.model3_bn.setSizePolicy(sizePolicy)
        self.model3_bn.setText("")
        self.model3_bn.setObjectName("model3_bn")
        self.verticalLayout_2.addWidget(self.model3_bn)
        self.model4_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model4_bn.sizePolicy().hasHeightForWidth())
        self.model4_bn.setSizePolicy(sizePolicy)
        self.model4_bn.setText("")
        self.model4_bn.setObjectName("model4_bn")
        self.verticalLayout_2.addWidget(self.model4_bn)
        self.model5_bn = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model5_bn.sizePolicy().hasHeightForWidth())
        self.model5_bn.setSizePolicy(sizePolicy)
        self.model5_bn.setText("")
        self.model5_bn.setObjectName("model5_bn")
        self.verticalLayout_2.addWidget(self.model5_bn)
        self.info_display = QPlainTextEdit(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_display.sizePolicy().hasHeightForWidth())
        self.info_display.setSizePolicy(sizePolicy)
        self.info_display.setReadOnly(True)
        self.info_display.setObjectName("info_display")
        self.verticalLayout_2.addWidget(self.info_display)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.setStretch(0, 10)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(2, 10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 9)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(4, 10)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.line_9 = QFrame(self.centralwidget)
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_5.addWidget(self.line_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("MainWindow")
        self.banner.setText("PriVision System")
